replicaCount: 1

image:
  repository: arajguru/example-02:0.0.2
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

namespace:
  name: example-2
  
labels:
  app:
    name: nginx
    version: 0.x.x
    env: dev