apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: my-nginx
  namespace: example-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: arajguru/example-01:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http