apiVersion: v1
kind: Service
metadata:
  name: fluxcd-examples-helm-app
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.labels.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      nodePort: {{ .Values.service.nodePort }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
        app: {{ .Values.labels.app.name }}
        version: {{ .Values.labels.app.version }}
        env: {{ .Values.labels.app.env }}
